name: gh-pages

on: [push]

jobs:
  to-gh-page:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run build
    - uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: 'dist'
